/*
Alfresco Content Services REST API

Testing DownloadsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/ahuret/goalfresco/openapi"
)

func Test_openapi_DownloadsApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DownloadsApiService CancelDownload", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var downloadId string

		httpRes, err := apiClient.DownloadsApi.CancelDownload(context.Background(), downloadId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DownloadsApiService CreateDownload", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DownloadsApi.CreateDownload(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DownloadsApiService GetDownload", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var downloadId string

		resp, httpRes, err := apiClient.DownloadsApi.GetDownload(context.Background(), downloadId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
