/*
Alfresco Content Services REST API

**Core API**  Provides access to the core features of Alfresco Content Services. 

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GroupBodyUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupBodyUpdate{}

// GroupBodyUpdate struct for GroupBodyUpdate
type GroupBodyUpdate struct {
	DisplayName string `json:"displayName"`
}

// NewGroupBodyUpdate instantiates a new GroupBodyUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupBodyUpdate(displayName string) *GroupBodyUpdate {
	this := GroupBodyUpdate{}
	this.DisplayName = displayName
	return &this
}

// NewGroupBodyUpdateWithDefaults instantiates a new GroupBodyUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupBodyUpdateWithDefaults() *GroupBodyUpdate {
	this := GroupBodyUpdate{}
	return &this
}

// GetDisplayName returns the DisplayName field value
func (o *GroupBodyUpdate) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *GroupBodyUpdate) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *GroupBodyUpdate) SetDisplayName(v string) {
	o.DisplayName = v
}

func (o GroupBodyUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupBodyUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["displayName"] = o.DisplayName
	return toSerialize, nil
}

type NullableGroupBodyUpdate struct {
	value *GroupBodyUpdate
	isSet bool
}

func (v NullableGroupBodyUpdate) Get() *GroupBodyUpdate {
	return v.value
}

func (v *NullableGroupBodyUpdate) Set(val *GroupBodyUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupBodyUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupBodyUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupBodyUpdate(val *GroupBodyUpdate) *NullableGroupBodyUpdate {
	return &NullableGroupBodyUpdate{value: val, isSet: true}
}

func (v NullableGroupBodyUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupBodyUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


