/*
Alfresco Content Services REST API

**Core API**  Provides access to the core features of Alfresco Content Services. 

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PersonNetworkPagingList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PersonNetworkPagingList{}

// PersonNetworkPagingList struct for PersonNetworkPagingList
type PersonNetworkPagingList struct {
	Pagination Pagination `json:"pagination"`
	Entries []PersonNetworkEntry `json:"entries"`
}

// NewPersonNetworkPagingList instantiates a new PersonNetworkPagingList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPersonNetworkPagingList(pagination Pagination, entries []PersonNetworkEntry) *PersonNetworkPagingList {
	this := PersonNetworkPagingList{}
	this.Pagination = pagination
	this.Entries = entries
	return &this
}

// NewPersonNetworkPagingListWithDefaults instantiates a new PersonNetworkPagingList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPersonNetworkPagingListWithDefaults() *PersonNetworkPagingList {
	this := PersonNetworkPagingList{}
	return &this
}

// GetPagination returns the Pagination field value
func (o *PersonNetworkPagingList) GetPagination() Pagination {
	if o == nil {
		var ret Pagination
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *PersonNetworkPagingList) GetPaginationOk() (*Pagination, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *PersonNetworkPagingList) SetPagination(v Pagination) {
	o.Pagination = v
}

// GetEntries returns the Entries field value
func (o *PersonNetworkPagingList) GetEntries() []PersonNetworkEntry {
	if o == nil {
		var ret []PersonNetworkEntry
		return ret
	}

	return o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value
// and a boolean to check if the value has been set.
func (o *PersonNetworkPagingList) GetEntriesOk() ([]PersonNetworkEntry, bool) {
	if o == nil {
		return nil, false
	}
	return o.Entries, true
}

// SetEntries sets field value
func (o *PersonNetworkPagingList) SetEntries(v []PersonNetworkEntry) {
	o.Entries = v
}

func (o PersonNetworkPagingList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PersonNetworkPagingList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pagination"] = o.Pagination
	toSerialize["entries"] = o.Entries
	return toSerialize, nil
}

type NullablePersonNetworkPagingList struct {
	value *PersonNetworkPagingList
	isSet bool
}

func (v NullablePersonNetworkPagingList) Get() *PersonNetworkPagingList {
	return v.value
}

func (v *NullablePersonNetworkPagingList) Set(val *PersonNetworkPagingList) {
	v.value = val
	v.isSet = true
}

func (v NullablePersonNetworkPagingList) IsSet() bool {
	return v.isSet
}

func (v *NullablePersonNetworkPagingList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePersonNetworkPagingList(val *PersonNetworkPagingList) *NullablePersonNetworkPagingList {
	return &NullablePersonNetworkPagingList{value: val, isSet: true}
}

func (v NullablePersonNetworkPagingList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePersonNetworkPagingList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


