/*
Alfresco Content Services REST API

**Core API**  Provides access to the core features of Alfresco Content Services. 

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SiteGroupPagingList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SiteGroupPagingList{}

// SiteGroupPagingList struct for SiteGroupPagingList
type SiteGroupPagingList struct {
	Pagination Pagination `json:"pagination"`
	Entries []SiteGroupEntry `json:"entries"`
}

// NewSiteGroupPagingList instantiates a new SiteGroupPagingList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSiteGroupPagingList(pagination Pagination, entries []SiteGroupEntry) *SiteGroupPagingList {
	this := SiteGroupPagingList{}
	this.Pagination = pagination
	this.Entries = entries
	return &this
}

// NewSiteGroupPagingListWithDefaults instantiates a new SiteGroupPagingList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSiteGroupPagingListWithDefaults() *SiteGroupPagingList {
	this := SiteGroupPagingList{}
	return &this
}

// GetPagination returns the Pagination field value
func (o *SiteGroupPagingList) GetPagination() Pagination {
	if o == nil {
		var ret Pagination
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *SiteGroupPagingList) GetPaginationOk() (*Pagination, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *SiteGroupPagingList) SetPagination(v Pagination) {
	o.Pagination = v
}

// GetEntries returns the Entries field value
func (o *SiteGroupPagingList) GetEntries() []SiteGroupEntry {
	if o == nil {
		var ret []SiteGroupEntry
		return ret
	}

	return o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value
// and a boolean to check if the value has been set.
func (o *SiteGroupPagingList) GetEntriesOk() ([]SiteGroupEntry, bool) {
	if o == nil {
		return nil, false
	}
	return o.Entries, true
}

// SetEntries sets field value
func (o *SiteGroupPagingList) SetEntries(v []SiteGroupEntry) {
	o.Entries = v
}

func (o SiteGroupPagingList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SiteGroupPagingList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pagination"] = o.Pagination
	toSerialize["entries"] = o.Entries
	return toSerialize, nil
}

type NullableSiteGroupPagingList struct {
	value *SiteGroupPagingList
	isSet bool
}

func (v NullableSiteGroupPagingList) Get() *SiteGroupPagingList {
	return v.value
}

func (v *NullableSiteGroupPagingList) Set(val *SiteGroupPagingList) {
	v.value = val
	v.isSet = true
}

func (v NullableSiteGroupPagingList) IsSet() bool {
	return v.isSet
}

func (v *NullableSiteGroupPagingList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSiteGroupPagingList(val *SiteGroupPagingList) *NullableSiteGroupPagingList {
	return &NullableSiteGroupPagingList{value: val, isSet: true}
}

func (v NullableSiteGroupPagingList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSiteGroupPagingList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


