/*
Alfresco Content Services REST API

**Core API**  Provides access to the core features of Alfresco Content Services. 

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"github.com/ahuret/goalfresco/time"
)

// checks if the Person type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Person{}

// Person struct for Person
type Person struct {
	Id string `json:"id"`
	FirstName string `json:"firstName"`
	LastName *string `json:"lastName,omitempty"`
	DisplayName *string `json:"displayName,omitempty"`
	Description *string `json:"description,omitempty"`
	AvatarId *string `json:"avatarId,omitempty"`
	Email string `json:"email"`
	SkypeId *string `json:"skypeId,omitempty"`
	GoogleId *string `json:"googleId,omitempty"`
	InstantMessageId *string `json:"instantMessageId,omitempty"`
	JobTitle *string `json:"jobTitle,omitempty"`
	Location *string `json:"location,omitempty"`
	Company *Company `json:"company,omitempty"`
	Mobile *string `json:"mobile,omitempty"`
	Telephone *string `json:"telephone,omitempty"`
	StatusUpdatedAt *time.Time `json:"statusUpdatedAt,omitempty"`
	UserStatus *string `json:"userStatus,omitempty"`
	Enabled bool `json:"enabled"`
	EmailNotificationsEnabled *bool `json:"emailNotificationsEnabled,omitempty"`
	AspectNames []string `json:"aspectNames,omitempty"`
	Properties map[string]interface{} `json:"properties,omitempty"`
	Capabilities *Capabilities `json:"capabilities,omitempty"`
}

// NewPerson instantiates a new Person object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPerson(id string, firstName string, email string, enabled bool) *Person {
	this := Person{}
	this.Id = id
	this.FirstName = firstName
	this.Email = email
	this.Enabled = enabled
	var emailNotificationsEnabled bool = true
	this.EmailNotificationsEnabled = &emailNotificationsEnabled
	return &this
}

// NewPersonWithDefaults instantiates a new Person object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPersonWithDefaults() *Person {
	this := Person{}
	var enabled bool = true
	this.Enabled = enabled
	var emailNotificationsEnabled bool = true
	this.EmailNotificationsEnabled = &emailNotificationsEnabled
	return &this
}

// GetId returns the Id field value
func (o *Person) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Person) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Person) SetId(v string) {
	o.Id = v
}

// GetFirstName returns the FirstName field value
func (o *Person) GetFirstName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value
// and a boolean to check if the value has been set.
func (o *Person) GetFirstNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstName, true
}

// SetFirstName sets field value
func (o *Person) SetFirstName(v string) {
	o.FirstName = v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *Person) GetLastName() string {
	if o == nil || IsNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Person) GetLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastName) {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *Person) HasLastName() bool {
	if o != nil && !IsNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *Person) SetLastName(v string) {
	o.LastName = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *Person) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Person) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *Person) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *Person) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Person) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Person) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Person) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Person) SetDescription(v string) {
	o.Description = &v
}

// GetAvatarId returns the AvatarId field value if set, zero value otherwise.
func (o *Person) GetAvatarId() string {
	if o == nil || IsNil(o.AvatarId) {
		var ret string
		return ret
	}
	return *o.AvatarId
}

// GetAvatarIdOk returns a tuple with the AvatarId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Person) GetAvatarIdOk() (*string, bool) {
	if o == nil || IsNil(o.AvatarId) {
		return nil, false
	}
	return o.AvatarId, true
}

// HasAvatarId returns a boolean if a field has been set.
func (o *Person) HasAvatarId() bool {
	if o != nil && !IsNil(o.AvatarId) {
		return true
	}

	return false
}

// SetAvatarId gets a reference to the given string and assigns it to the AvatarId field.
func (o *Person) SetAvatarId(v string) {
	o.AvatarId = &v
}

// GetEmail returns the Email field value
func (o *Person) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *Person) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *Person) SetEmail(v string) {
	o.Email = v
}

// GetSkypeId returns the SkypeId field value if set, zero value otherwise.
func (o *Person) GetSkypeId() string {
	if o == nil || IsNil(o.SkypeId) {
		var ret string
		return ret
	}
	return *o.SkypeId
}

// GetSkypeIdOk returns a tuple with the SkypeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Person) GetSkypeIdOk() (*string, bool) {
	if o == nil || IsNil(o.SkypeId) {
		return nil, false
	}
	return o.SkypeId, true
}

// HasSkypeId returns a boolean if a field has been set.
func (o *Person) HasSkypeId() bool {
	if o != nil && !IsNil(o.SkypeId) {
		return true
	}

	return false
}

// SetSkypeId gets a reference to the given string and assigns it to the SkypeId field.
func (o *Person) SetSkypeId(v string) {
	o.SkypeId = &v
}

// GetGoogleId returns the GoogleId field value if set, zero value otherwise.
func (o *Person) GetGoogleId() string {
	if o == nil || IsNil(o.GoogleId) {
		var ret string
		return ret
	}
	return *o.GoogleId
}

// GetGoogleIdOk returns a tuple with the GoogleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Person) GetGoogleIdOk() (*string, bool) {
	if o == nil || IsNil(o.GoogleId) {
		return nil, false
	}
	return o.GoogleId, true
}

// HasGoogleId returns a boolean if a field has been set.
func (o *Person) HasGoogleId() bool {
	if o != nil && !IsNil(o.GoogleId) {
		return true
	}

	return false
}

// SetGoogleId gets a reference to the given string and assigns it to the GoogleId field.
func (o *Person) SetGoogleId(v string) {
	o.GoogleId = &v
}

// GetInstantMessageId returns the InstantMessageId field value if set, zero value otherwise.
func (o *Person) GetInstantMessageId() string {
	if o == nil || IsNil(o.InstantMessageId) {
		var ret string
		return ret
	}
	return *o.InstantMessageId
}

// GetInstantMessageIdOk returns a tuple with the InstantMessageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Person) GetInstantMessageIdOk() (*string, bool) {
	if o == nil || IsNil(o.InstantMessageId) {
		return nil, false
	}
	return o.InstantMessageId, true
}

// HasInstantMessageId returns a boolean if a field has been set.
func (o *Person) HasInstantMessageId() bool {
	if o != nil && !IsNil(o.InstantMessageId) {
		return true
	}

	return false
}

// SetInstantMessageId gets a reference to the given string and assigns it to the InstantMessageId field.
func (o *Person) SetInstantMessageId(v string) {
	o.InstantMessageId = &v
}

// GetJobTitle returns the JobTitle field value if set, zero value otherwise.
func (o *Person) GetJobTitle() string {
	if o == nil || IsNil(o.JobTitle) {
		var ret string
		return ret
	}
	return *o.JobTitle
}

// GetJobTitleOk returns a tuple with the JobTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Person) GetJobTitleOk() (*string, bool) {
	if o == nil || IsNil(o.JobTitle) {
		return nil, false
	}
	return o.JobTitle, true
}

// HasJobTitle returns a boolean if a field has been set.
func (o *Person) HasJobTitle() bool {
	if o != nil && !IsNil(o.JobTitle) {
		return true
	}

	return false
}

// SetJobTitle gets a reference to the given string and assigns it to the JobTitle field.
func (o *Person) SetJobTitle(v string) {
	o.JobTitle = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *Person) GetLocation() string {
	if o == nil || IsNil(o.Location) {
		var ret string
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Person) GetLocationOk() (*string, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *Person) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given string and assigns it to the Location field.
func (o *Person) SetLocation(v string) {
	o.Location = &v
}

// GetCompany returns the Company field value if set, zero value otherwise.
func (o *Person) GetCompany() Company {
	if o == nil || IsNil(o.Company) {
		var ret Company
		return ret
	}
	return *o.Company
}

// GetCompanyOk returns a tuple with the Company field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Person) GetCompanyOk() (*Company, bool) {
	if o == nil || IsNil(o.Company) {
		return nil, false
	}
	return o.Company, true
}

// HasCompany returns a boolean if a field has been set.
func (o *Person) HasCompany() bool {
	if o != nil && !IsNil(o.Company) {
		return true
	}

	return false
}

// SetCompany gets a reference to the given Company and assigns it to the Company field.
func (o *Person) SetCompany(v Company) {
	o.Company = &v
}

// GetMobile returns the Mobile field value if set, zero value otherwise.
func (o *Person) GetMobile() string {
	if o == nil || IsNil(o.Mobile) {
		var ret string
		return ret
	}
	return *o.Mobile
}

// GetMobileOk returns a tuple with the Mobile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Person) GetMobileOk() (*string, bool) {
	if o == nil || IsNil(o.Mobile) {
		return nil, false
	}
	return o.Mobile, true
}

// HasMobile returns a boolean if a field has been set.
func (o *Person) HasMobile() bool {
	if o != nil && !IsNil(o.Mobile) {
		return true
	}

	return false
}

// SetMobile gets a reference to the given string and assigns it to the Mobile field.
func (o *Person) SetMobile(v string) {
	o.Mobile = &v
}

// GetTelephone returns the Telephone field value if set, zero value otherwise.
func (o *Person) GetTelephone() string {
	if o == nil || IsNil(o.Telephone) {
		var ret string
		return ret
	}
	return *o.Telephone
}

// GetTelephoneOk returns a tuple with the Telephone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Person) GetTelephoneOk() (*string, bool) {
	if o == nil || IsNil(o.Telephone) {
		return nil, false
	}
	return o.Telephone, true
}

// HasTelephone returns a boolean if a field has been set.
func (o *Person) HasTelephone() bool {
	if o != nil && !IsNil(o.Telephone) {
		return true
	}

	return false
}

// SetTelephone gets a reference to the given string and assigns it to the Telephone field.
func (o *Person) SetTelephone(v string) {
	o.Telephone = &v
}

// GetStatusUpdatedAt returns the StatusUpdatedAt field value if set, zero value otherwise.
func (o *Person) GetStatusUpdatedAt() time.Time {
	if o == nil || IsNil(o.StatusUpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.StatusUpdatedAt
}

// GetStatusUpdatedAtOk returns a tuple with the StatusUpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Person) GetStatusUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StatusUpdatedAt) {
		return nil, false
	}
	return o.StatusUpdatedAt, true
}

// HasStatusUpdatedAt returns a boolean if a field has been set.
func (o *Person) HasStatusUpdatedAt() bool {
	if o != nil && !IsNil(o.StatusUpdatedAt) {
		return true
	}

	return false
}

// SetStatusUpdatedAt gets a reference to the given time.Time and assigns it to the StatusUpdatedAt field.
func (o *Person) SetStatusUpdatedAt(v time.Time) {
	o.StatusUpdatedAt = &v
}

// GetUserStatus returns the UserStatus field value if set, zero value otherwise.
func (o *Person) GetUserStatus() string {
	if o == nil || IsNil(o.UserStatus) {
		var ret string
		return ret
	}
	return *o.UserStatus
}

// GetUserStatusOk returns a tuple with the UserStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Person) GetUserStatusOk() (*string, bool) {
	if o == nil || IsNil(o.UserStatus) {
		return nil, false
	}
	return o.UserStatus, true
}

// HasUserStatus returns a boolean if a field has been set.
func (o *Person) HasUserStatus() bool {
	if o != nil && !IsNil(o.UserStatus) {
		return true
	}

	return false
}

// SetUserStatus gets a reference to the given string and assigns it to the UserStatus field.
func (o *Person) SetUserStatus(v string) {
	o.UserStatus = &v
}

// GetEnabled returns the Enabled field value
func (o *Person) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *Person) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *Person) SetEnabled(v bool) {
	o.Enabled = v
}

// GetEmailNotificationsEnabled returns the EmailNotificationsEnabled field value if set, zero value otherwise.
func (o *Person) GetEmailNotificationsEnabled() bool {
	if o == nil || IsNil(o.EmailNotificationsEnabled) {
		var ret bool
		return ret
	}
	return *o.EmailNotificationsEnabled
}

// GetEmailNotificationsEnabledOk returns a tuple with the EmailNotificationsEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Person) GetEmailNotificationsEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.EmailNotificationsEnabled) {
		return nil, false
	}
	return o.EmailNotificationsEnabled, true
}

// HasEmailNotificationsEnabled returns a boolean if a field has been set.
func (o *Person) HasEmailNotificationsEnabled() bool {
	if o != nil && !IsNil(o.EmailNotificationsEnabled) {
		return true
	}

	return false
}

// SetEmailNotificationsEnabled gets a reference to the given bool and assigns it to the EmailNotificationsEnabled field.
func (o *Person) SetEmailNotificationsEnabled(v bool) {
	o.EmailNotificationsEnabled = &v
}

// GetAspectNames returns the AspectNames field value if set, zero value otherwise.
func (o *Person) GetAspectNames() []string {
	if o == nil || IsNil(o.AspectNames) {
		var ret []string
		return ret
	}
	return o.AspectNames
}

// GetAspectNamesOk returns a tuple with the AspectNames field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Person) GetAspectNamesOk() ([]string, bool) {
	if o == nil || IsNil(o.AspectNames) {
		return nil, false
	}
	return o.AspectNames, true
}

// HasAspectNames returns a boolean if a field has been set.
func (o *Person) HasAspectNames() bool {
	if o != nil && !IsNil(o.AspectNames) {
		return true
	}

	return false
}

// SetAspectNames gets a reference to the given []string and assigns it to the AspectNames field.
func (o *Person) SetAspectNames(v []string) {
	o.AspectNames = v
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *Person) GetProperties() map[string]interface{} {
	if o == nil || IsNil(o.Properties) {
		var ret map[string]interface{}
		return ret
	}
	return o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Person) GetPropertiesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Properties) {
		return map[string]interface{}{}, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *Person) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given map[string]interface{} and assigns it to the Properties field.
func (o *Person) SetProperties(v map[string]interface{}) {
	o.Properties = v
}

// GetCapabilities returns the Capabilities field value if set, zero value otherwise.
func (o *Person) GetCapabilities() Capabilities {
	if o == nil || IsNil(o.Capabilities) {
		var ret Capabilities
		return ret
	}
	return *o.Capabilities
}

// GetCapabilitiesOk returns a tuple with the Capabilities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Person) GetCapabilitiesOk() (*Capabilities, bool) {
	if o == nil || IsNil(o.Capabilities) {
		return nil, false
	}
	return o.Capabilities, true
}

// HasCapabilities returns a boolean if a field has been set.
func (o *Person) HasCapabilities() bool {
	if o != nil && !IsNil(o.Capabilities) {
		return true
	}

	return false
}

// SetCapabilities gets a reference to the given Capabilities and assigns it to the Capabilities field.
func (o *Person) SetCapabilities(v Capabilities) {
	o.Capabilities = &v
}

func (o Person) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Person) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["firstName"] = o.FirstName
	if !IsNil(o.LastName) {
		toSerialize["lastName"] = o.LastName
	}
	if !IsNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.AvatarId) {
		toSerialize["avatarId"] = o.AvatarId
	}
	toSerialize["email"] = o.Email
	if !IsNil(o.SkypeId) {
		toSerialize["skypeId"] = o.SkypeId
	}
	if !IsNil(o.GoogleId) {
		toSerialize["googleId"] = o.GoogleId
	}
	if !IsNil(o.InstantMessageId) {
		toSerialize["instantMessageId"] = o.InstantMessageId
	}
	if !IsNil(o.JobTitle) {
		toSerialize["jobTitle"] = o.JobTitle
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.Company) {
		toSerialize["company"] = o.Company
	}
	if !IsNil(o.Mobile) {
		toSerialize["mobile"] = o.Mobile
	}
	if !IsNil(o.Telephone) {
		toSerialize["telephone"] = o.Telephone
	}
	if !IsNil(o.StatusUpdatedAt) {
		toSerialize["statusUpdatedAt"] = o.StatusUpdatedAt
	}
	if !IsNil(o.UserStatus) {
		toSerialize["userStatus"] = o.UserStatus
	}
	toSerialize["enabled"] = o.Enabled
	if !IsNil(o.EmailNotificationsEnabled) {
		toSerialize["emailNotificationsEnabled"] = o.EmailNotificationsEnabled
	}
	if !IsNil(o.AspectNames) {
		toSerialize["aspectNames"] = o.AspectNames
	}
	if !IsNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}
	if !IsNil(o.Capabilities) {
		toSerialize["capabilities"] = o.Capabilities
	}
	return toSerialize, nil
}

type NullablePerson struct {
	value *Person
	isSet bool
}

func (v NullablePerson) Get() *Person {
	return v.value
}

func (v *NullablePerson) Set(val *Person) {
	v.value = val
	v.isSet = true
}

func (v NullablePerson) IsSet() bool {
	return v.isSet
}

func (v *NullablePerson) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePerson(val *Person) *NullablePerson {
	return &NullablePerson{value: val, isSet: true}
}

func (v NullablePerson) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePerson) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


