/*
Alfresco Content Services REST API

**Core API**  Provides access to the core features of Alfresco Content Services. 

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SiteMemberEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SiteMemberEntry{}

// SiteMemberEntry struct for SiteMemberEntry
type SiteMemberEntry struct {
	Entry SiteMember `json:"entry"`
}

// NewSiteMemberEntry instantiates a new SiteMemberEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSiteMemberEntry(entry SiteMember) *SiteMemberEntry {
	this := SiteMemberEntry{}
	this.Entry = entry
	return &this
}

// NewSiteMemberEntryWithDefaults instantiates a new SiteMemberEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSiteMemberEntryWithDefaults() *SiteMemberEntry {
	this := SiteMemberEntry{}
	return &this
}

// GetEntry returns the Entry field value
func (o *SiteMemberEntry) GetEntry() SiteMember {
	if o == nil {
		var ret SiteMember
		return ret
	}

	return o.Entry
}

// GetEntryOk returns a tuple with the Entry field value
// and a boolean to check if the value has been set.
func (o *SiteMemberEntry) GetEntryOk() (*SiteMember, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Entry, true
}

// SetEntry sets field value
func (o *SiteMemberEntry) SetEntry(v SiteMember) {
	o.Entry = v
}

func (o SiteMemberEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SiteMemberEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["entry"] = o.Entry
	return toSerialize, nil
}

type NullableSiteMemberEntry struct {
	value *SiteMemberEntry
	isSet bool
}

func (v NullableSiteMemberEntry) Get() *SiteMemberEntry {
	return v.value
}

func (v *NullableSiteMemberEntry) Set(val *SiteMemberEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableSiteMemberEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableSiteMemberEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSiteMemberEntry(val *SiteMemberEntry) *NullableSiteMemberEntry {
	return &NullableSiteMemberEntry{value: val, isSet: true}
}

func (v NullableSiteMemberEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSiteMemberEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


