/*
Alfresco Content Services REST API

**Core API**  Provides access to the core features of Alfresco Content Services. 

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AuditBodyUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuditBodyUpdate{}

// AuditBodyUpdate struct for AuditBodyUpdate
type AuditBodyUpdate struct {
	IsEnabled *bool `json:"isEnabled,omitempty"`
}

// NewAuditBodyUpdate instantiates a new AuditBodyUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuditBodyUpdate() *AuditBodyUpdate {
	this := AuditBodyUpdate{}
	return &this
}

// NewAuditBodyUpdateWithDefaults instantiates a new AuditBodyUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuditBodyUpdateWithDefaults() *AuditBodyUpdate {
	this := AuditBodyUpdate{}
	return &this
}

// GetIsEnabled returns the IsEnabled field value if set, zero value otherwise.
func (o *AuditBodyUpdate) GetIsEnabled() bool {
	if o == nil || IsNil(o.IsEnabled) {
		var ret bool
		return ret
	}
	return *o.IsEnabled
}

// GetIsEnabledOk returns a tuple with the IsEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuditBodyUpdate) GetIsEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsEnabled) {
		return nil, false
	}
	return o.IsEnabled, true
}

// HasIsEnabled returns a boolean if a field has been set.
func (o *AuditBodyUpdate) HasIsEnabled() bool {
	if o != nil && !IsNil(o.IsEnabled) {
		return true
	}

	return false
}

// SetIsEnabled gets a reference to the given bool and assigns it to the IsEnabled field.
func (o *AuditBodyUpdate) SetIsEnabled(v bool) {
	o.IsEnabled = &v
}

func (o AuditBodyUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuditBodyUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IsEnabled) {
		toSerialize["isEnabled"] = o.IsEnabled
	}
	return toSerialize, nil
}

type NullableAuditBodyUpdate struct {
	value *AuditBodyUpdate
	isSet bool
}

func (v NullableAuditBodyUpdate) Get() *AuditBodyUpdate {
	return v.value
}

func (v *NullableAuditBodyUpdate) Set(val *AuditBodyUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableAuditBodyUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableAuditBodyUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuditBodyUpdate(val *AuditBodyUpdate) *NullableAuditBodyUpdate {
	return &NullableAuditBodyUpdate{value: val, isSet: true}
}

func (v NullableAuditBodyUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuditBodyUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


