/*
Alfresco Content Services REST API

**Core API**  Provides access to the core features of Alfresco Content Services. 

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SiteMembershipRequestWithPersonPagingList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SiteMembershipRequestWithPersonPagingList{}

// SiteMembershipRequestWithPersonPagingList struct for SiteMembershipRequestWithPersonPagingList
type SiteMembershipRequestWithPersonPagingList struct {
	Pagination Pagination `json:"pagination"`
	Entries []SiteMembershipRequestWithPersonEntry `json:"entries"`
}

// NewSiteMembershipRequestWithPersonPagingList instantiates a new SiteMembershipRequestWithPersonPagingList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSiteMembershipRequestWithPersonPagingList(pagination Pagination, entries []SiteMembershipRequestWithPersonEntry) *SiteMembershipRequestWithPersonPagingList {
	this := SiteMembershipRequestWithPersonPagingList{}
	this.Pagination = pagination
	this.Entries = entries
	return &this
}

// NewSiteMembershipRequestWithPersonPagingListWithDefaults instantiates a new SiteMembershipRequestWithPersonPagingList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSiteMembershipRequestWithPersonPagingListWithDefaults() *SiteMembershipRequestWithPersonPagingList {
	this := SiteMembershipRequestWithPersonPagingList{}
	return &this
}

// GetPagination returns the Pagination field value
func (o *SiteMembershipRequestWithPersonPagingList) GetPagination() Pagination {
	if o == nil {
		var ret Pagination
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *SiteMembershipRequestWithPersonPagingList) GetPaginationOk() (*Pagination, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *SiteMembershipRequestWithPersonPagingList) SetPagination(v Pagination) {
	o.Pagination = v
}

// GetEntries returns the Entries field value
func (o *SiteMembershipRequestWithPersonPagingList) GetEntries() []SiteMembershipRequestWithPersonEntry {
	if o == nil {
		var ret []SiteMembershipRequestWithPersonEntry
		return ret
	}

	return o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value
// and a boolean to check if the value has been set.
func (o *SiteMembershipRequestWithPersonPagingList) GetEntriesOk() ([]SiteMembershipRequestWithPersonEntry, bool) {
	if o == nil {
		return nil, false
	}
	return o.Entries, true
}

// SetEntries sets field value
func (o *SiteMembershipRequestWithPersonPagingList) SetEntries(v []SiteMembershipRequestWithPersonEntry) {
	o.Entries = v
}

func (o SiteMembershipRequestWithPersonPagingList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SiteMembershipRequestWithPersonPagingList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pagination"] = o.Pagination
	toSerialize["entries"] = o.Entries
	return toSerialize, nil
}

type NullableSiteMembershipRequestWithPersonPagingList struct {
	value *SiteMembershipRequestWithPersonPagingList
	isSet bool
}

func (v NullableSiteMembershipRequestWithPersonPagingList) Get() *SiteMembershipRequestWithPersonPagingList {
	return v.value
}

func (v *NullableSiteMembershipRequestWithPersonPagingList) Set(val *SiteMembershipRequestWithPersonPagingList) {
	v.value = val
	v.isSet = true
}

func (v NullableSiteMembershipRequestWithPersonPagingList) IsSet() bool {
	return v.isSet
}

func (v *NullableSiteMembershipRequestWithPersonPagingList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSiteMembershipRequestWithPersonPagingList(val *SiteMembershipRequestWithPersonPagingList) *NullableSiteMembershipRequestWithPersonPagingList {
	return &NullableSiteMembershipRequestWithPersonPagingList{value: val, isSet: true}
}

func (v NullableSiteMembershipRequestWithPersonPagingList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSiteMembershipRequestWithPersonPagingList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


