/*
Alfresco Content Services REST API

**Core API**  Provides access to the core features of Alfresco Content Services. 

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TagEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TagEntry{}

// TagEntry struct for TagEntry
type TagEntry struct {
	Entry Tag `json:"entry"`
}

// NewTagEntry instantiates a new TagEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTagEntry(entry Tag) *TagEntry {
	this := TagEntry{}
	this.Entry = entry
	return &this
}

// NewTagEntryWithDefaults instantiates a new TagEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTagEntryWithDefaults() *TagEntry {
	this := TagEntry{}
	return &this
}

// GetEntry returns the Entry field value
func (o *TagEntry) GetEntry() Tag {
	if o == nil {
		var ret Tag
		return ret
	}

	return o.Entry
}

// GetEntryOk returns a tuple with the Entry field value
// and a boolean to check if the value has been set.
func (o *TagEntry) GetEntryOk() (*Tag, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Entry, true
}

// SetEntry sets field value
func (o *TagEntry) SetEntry(v Tag) {
	o.Entry = v
}

func (o TagEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TagEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["entry"] = o.Entry
	return toSerialize, nil
}

type NullableTagEntry struct {
	value *TagEntry
	isSet bool
}

func (v NullableTagEntry) Get() *TagEntry {
	return v.value
}

func (v *NullableTagEntry) Set(val *TagEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableTagEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableTagEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTagEntry(val *TagEntry) *NullableTagEntry {
	return &NullableTagEntry{value: val, isSet: true}
}

func (v NullableTagEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTagEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


