/*
Alfresco Content Services REST API

**Core API**  Provides access to the core features of Alfresco Content Services. 

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SiteGroupPaging type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SiteGroupPaging{}

// SiteGroupPaging struct for SiteGroupPaging
type SiteGroupPaging struct {
	List SiteGroupPagingList `json:"list"`
}

// NewSiteGroupPaging instantiates a new SiteGroupPaging object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSiteGroupPaging(list SiteGroupPagingList) *SiteGroupPaging {
	this := SiteGroupPaging{}
	this.List = list
	return &this
}

// NewSiteGroupPagingWithDefaults instantiates a new SiteGroupPaging object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSiteGroupPagingWithDefaults() *SiteGroupPaging {
	this := SiteGroupPaging{}
	return &this
}

// GetList returns the List field value
func (o *SiteGroupPaging) GetList() SiteGroupPagingList {
	if o == nil {
		var ret SiteGroupPagingList
		return ret
	}

	return o.List
}

// GetListOk returns a tuple with the List field value
// and a boolean to check if the value has been set.
func (o *SiteGroupPaging) GetListOk() (*SiteGroupPagingList, bool) {
	if o == nil {
		return nil, false
	}
	return &o.List, true
}

// SetList sets field value
func (o *SiteGroupPaging) SetList(v SiteGroupPagingList) {
	o.List = v
}

func (o SiteGroupPaging) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SiteGroupPaging) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["list"] = o.List
	return toSerialize, nil
}

type NullableSiteGroupPaging struct {
	value *SiteGroupPaging
	isSet bool
}

func (v NullableSiteGroupPaging) Get() *SiteGroupPaging {
	return v.value
}

func (v *NullableSiteGroupPaging) Set(val *SiteGroupPaging) {
	v.value = val
	v.isSet = true
}

func (v NullableSiteGroupPaging) IsSet() bool {
	return v.isSet
}

func (v *NullableSiteGroupPaging) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSiteGroupPaging(val *SiteGroupPaging) *NullableSiteGroupPaging {
	return &NullableSiteGroupPaging{value: val, isSet: true}
}

func (v NullableSiteGroupPaging) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSiteGroupPaging) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


