/*
Alfresco Content Services REST API

**Core API**  Provides access to the core features of Alfresco Content Services. 

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"github.com/ahuret/goalfresco/time"
)

// checks if the SiteMembershipRequestWithPerson type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SiteMembershipRequestWithPerson{}

// SiteMembershipRequestWithPerson struct for SiteMembershipRequestWithPerson
type SiteMembershipRequestWithPerson struct {
	Id string `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
	Site Site `json:"site"`
	Person Person `json:"person"`
	Message *string `json:"message,omitempty"`
}

// NewSiteMembershipRequestWithPerson instantiates a new SiteMembershipRequestWithPerson object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSiteMembershipRequestWithPerson(id string, createdAt time.Time, site Site, person Person) *SiteMembershipRequestWithPerson {
	this := SiteMembershipRequestWithPerson{}
	this.Id = id
	this.CreatedAt = createdAt
	this.Site = site
	this.Person = person
	return &this
}

// NewSiteMembershipRequestWithPersonWithDefaults instantiates a new SiteMembershipRequestWithPerson object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSiteMembershipRequestWithPersonWithDefaults() *SiteMembershipRequestWithPerson {
	this := SiteMembershipRequestWithPerson{}
	return &this
}

// GetId returns the Id field value
func (o *SiteMembershipRequestWithPerson) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SiteMembershipRequestWithPerson) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SiteMembershipRequestWithPerson) SetId(v string) {
	o.Id = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *SiteMembershipRequestWithPerson) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *SiteMembershipRequestWithPerson) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *SiteMembershipRequestWithPerson) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetSite returns the Site field value
func (o *SiteMembershipRequestWithPerson) GetSite() Site {
	if o == nil {
		var ret Site
		return ret
	}

	return o.Site
}

// GetSiteOk returns a tuple with the Site field value
// and a boolean to check if the value has been set.
func (o *SiteMembershipRequestWithPerson) GetSiteOk() (*Site, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Site, true
}

// SetSite sets field value
func (o *SiteMembershipRequestWithPerson) SetSite(v Site) {
	o.Site = v
}

// GetPerson returns the Person field value
func (o *SiteMembershipRequestWithPerson) GetPerson() Person {
	if o == nil {
		var ret Person
		return ret
	}

	return o.Person
}

// GetPersonOk returns a tuple with the Person field value
// and a boolean to check if the value has been set.
func (o *SiteMembershipRequestWithPerson) GetPersonOk() (*Person, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Person, true
}

// SetPerson sets field value
func (o *SiteMembershipRequestWithPerson) SetPerson(v Person) {
	o.Person = v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *SiteMembershipRequestWithPerson) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteMembershipRequestWithPerson) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *SiteMembershipRequestWithPerson) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *SiteMembershipRequestWithPerson) SetMessage(v string) {
	o.Message = &v
}

func (o SiteMembershipRequestWithPerson) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SiteMembershipRequestWithPerson) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["site"] = o.Site
	toSerialize["person"] = o.Person
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableSiteMembershipRequestWithPerson struct {
	value *SiteMembershipRequestWithPerson
	isSet bool
}

func (v NullableSiteMembershipRequestWithPerson) Get() *SiteMembershipRequestWithPerson {
	return v.value
}

func (v *NullableSiteMembershipRequestWithPerson) Set(val *SiteMembershipRequestWithPerson) {
	v.value = val
	v.isSet = true
}

func (v NullableSiteMembershipRequestWithPerson) IsSet() bool {
	return v.isSet
}

func (v *NullableSiteMembershipRequestWithPerson) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSiteMembershipRequestWithPerson(val *SiteMembershipRequestWithPerson) *NullableSiteMembershipRequestWithPerson {
	return &NullableSiteMembershipRequestWithPerson{value: val, isSet: true}
}

func (v NullableSiteMembershipRequestWithPerson) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSiteMembershipRequestWithPerson) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


