/*
Alfresco Content Services REST API

**Core API**  Provides access to the core features of Alfresco Content Services. 

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SiteMembershipBodyUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SiteMembershipBodyUpdate{}

// SiteMembershipBodyUpdate struct for SiteMembershipBodyUpdate
type SiteMembershipBodyUpdate struct {
	Role string `json:"role"`
}

// NewSiteMembershipBodyUpdate instantiates a new SiteMembershipBodyUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSiteMembershipBodyUpdate(role string) *SiteMembershipBodyUpdate {
	this := SiteMembershipBodyUpdate{}
	this.Role = role
	return &this
}

// NewSiteMembershipBodyUpdateWithDefaults instantiates a new SiteMembershipBodyUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSiteMembershipBodyUpdateWithDefaults() *SiteMembershipBodyUpdate {
	this := SiteMembershipBodyUpdate{}
	return &this
}

// GetRole returns the Role field value
func (o *SiteMembershipBodyUpdate) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *SiteMembershipBodyUpdate) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *SiteMembershipBodyUpdate) SetRole(v string) {
	o.Role = v
}

func (o SiteMembershipBodyUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SiteMembershipBodyUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["role"] = o.Role
	return toSerialize, nil
}

type NullableSiteMembershipBodyUpdate struct {
	value *SiteMembershipBodyUpdate
	isSet bool
}

func (v NullableSiteMembershipBodyUpdate) Get() *SiteMembershipBodyUpdate {
	return v.value
}

func (v *NullableSiteMembershipBodyUpdate) Set(val *SiteMembershipBodyUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableSiteMembershipBodyUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableSiteMembershipBodyUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSiteMembershipBodyUpdate(val *SiteMembershipBodyUpdate) *NullableSiteMembershipBodyUpdate {
	return &NullableSiteMembershipBodyUpdate{value: val, isSet: true}
}

func (v NullableSiteMembershipBodyUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSiteMembershipBodyUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


