/*
Alfresco Content Services REST API

**Core API**  Provides access to the core features of Alfresco Content Services. 

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SiteContainerPagingList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SiteContainerPagingList{}

// SiteContainerPagingList struct for SiteContainerPagingList
type SiteContainerPagingList struct {
	Pagination Pagination `json:"pagination"`
	Entries []SiteContainerEntry `json:"entries"`
}

// NewSiteContainerPagingList instantiates a new SiteContainerPagingList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSiteContainerPagingList(pagination Pagination, entries []SiteContainerEntry) *SiteContainerPagingList {
	this := SiteContainerPagingList{}
	this.Pagination = pagination
	this.Entries = entries
	return &this
}

// NewSiteContainerPagingListWithDefaults instantiates a new SiteContainerPagingList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSiteContainerPagingListWithDefaults() *SiteContainerPagingList {
	this := SiteContainerPagingList{}
	return &this
}

// GetPagination returns the Pagination field value
func (o *SiteContainerPagingList) GetPagination() Pagination {
	if o == nil {
		var ret Pagination
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *SiteContainerPagingList) GetPaginationOk() (*Pagination, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *SiteContainerPagingList) SetPagination(v Pagination) {
	o.Pagination = v
}

// GetEntries returns the Entries field value
func (o *SiteContainerPagingList) GetEntries() []SiteContainerEntry {
	if o == nil {
		var ret []SiteContainerEntry
		return ret
	}

	return o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value
// and a boolean to check if the value has been set.
func (o *SiteContainerPagingList) GetEntriesOk() ([]SiteContainerEntry, bool) {
	if o == nil {
		return nil, false
	}
	return o.Entries, true
}

// SetEntries sets field value
func (o *SiteContainerPagingList) SetEntries(v []SiteContainerEntry) {
	o.Entries = v
}

func (o SiteContainerPagingList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SiteContainerPagingList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pagination"] = o.Pagination
	toSerialize["entries"] = o.Entries
	return toSerialize, nil
}

type NullableSiteContainerPagingList struct {
	value *SiteContainerPagingList
	isSet bool
}

func (v NullableSiteContainerPagingList) Get() *SiteContainerPagingList {
	return v.value
}

func (v *NullableSiteContainerPagingList) Set(val *SiteContainerPagingList) {
	v.value = val
	v.isSet = true
}

func (v NullableSiteContainerPagingList) IsSet() bool {
	return v.isSet
}

func (v *NullableSiteContainerPagingList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSiteContainerPagingList(val *SiteContainerPagingList) *NullableSiteContainerPagingList {
	return &NullableSiteContainerPagingList{value: val, isSet: true}
}

func (v NullableSiteContainerPagingList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSiteContainerPagingList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


