/*
Alfresco Content Services REST API

**Core API**  Provides access to the core features of Alfresco Content Services. 

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the NodePagingList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodePagingList{}

// NodePagingList struct for NodePagingList
type NodePagingList struct {
	Pagination *Pagination `json:"pagination,omitempty"`
	Entries []NodeEntry `json:"entries,omitempty"`
	Source *Node `json:"source,omitempty"`
}

// NewNodePagingList instantiates a new NodePagingList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodePagingList() *NodePagingList {
	this := NodePagingList{}
	return &this
}

// NewNodePagingListWithDefaults instantiates a new NodePagingList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodePagingListWithDefaults() *NodePagingList {
	this := NodePagingList{}
	return &this
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *NodePagingList) GetPagination() Pagination {
	if o == nil || IsNil(o.Pagination) {
		var ret Pagination
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodePagingList) GetPaginationOk() (*Pagination, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *NodePagingList) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given Pagination and assigns it to the Pagination field.
func (o *NodePagingList) SetPagination(v Pagination) {
	o.Pagination = &v
}

// GetEntries returns the Entries field value if set, zero value otherwise.
func (o *NodePagingList) GetEntries() []NodeEntry {
	if o == nil || IsNil(o.Entries) {
		var ret []NodeEntry
		return ret
	}
	return o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodePagingList) GetEntriesOk() ([]NodeEntry, bool) {
	if o == nil || IsNil(o.Entries) {
		return nil, false
	}
	return o.Entries, true
}

// HasEntries returns a boolean if a field has been set.
func (o *NodePagingList) HasEntries() bool {
	if o != nil && !IsNil(o.Entries) {
		return true
	}

	return false
}

// SetEntries gets a reference to the given []NodeEntry and assigns it to the Entries field.
func (o *NodePagingList) SetEntries(v []NodeEntry) {
	o.Entries = v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *NodePagingList) GetSource() Node {
	if o == nil || IsNil(o.Source) {
		var ret Node
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NodePagingList) GetSourceOk() (*Node, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *NodePagingList) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given Node and assigns it to the Source field.
func (o *NodePagingList) SetSource(v Node) {
	o.Source = &v
}

func (o NodePagingList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodePagingList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}
	if !IsNil(o.Entries) {
		toSerialize["entries"] = o.Entries
	}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	return toSerialize, nil
}

type NullableNodePagingList struct {
	value *NodePagingList
	isSet bool
}

func (v NullableNodePagingList) Get() *NodePagingList {
	return v.value
}

func (v *NullableNodePagingList) Set(val *NodePagingList) {
	v.value = val
	v.isSet = true
}

func (v NullableNodePagingList) IsSet() bool {
	return v.isSet
}

func (v *NullableNodePagingList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodePagingList(val *NodePagingList) *NullableNodePagingList {
	return &NullableNodePagingList{value: val, isSet: true}
}

func (v NullableNodePagingList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodePagingList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


