/*
Alfresco Content Services REST API

**Core API**  Provides access to the core features of Alfresco Content Services. 

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the NodeChildAssociationEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodeChildAssociationEntry{}

// NodeChildAssociationEntry struct for NodeChildAssociationEntry
type NodeChildAssociationEntry struct {
	Entry NodeChildAssociation `json:"entry"`
}

// NewNodeChildAssociationEntry instantiates a new NodeChildAssociationEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodeChildAssociationEntry(entry NodeChildAssociation) *NodeChildAssociationEntry {
	this := NodeChildAssociationEntry{}
	this.Entry = entry
	return &this
}

// NewNodeChildAssociationEntryWithDefaults instantiates a new NodeChildAssociationEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodeChildAssociationEntryWithDefaults() *NodeChildAssociationEntry {
	this := NodeChildAssociationEntry{}
	return &this
}

// GetEntry returns the Entry field value
func (o *NodeChildAssociationEntry) GetEntry() NodeChildAssociation {
	if o == nil {
		var ret NodeChildAssociation
		return ret
	}

	return o.Entry
}

// GetEntryOk returns a tuple with the Entry field value
// and a boolean to check if the value has been set.
func (o *NodeChildAssociationEntry) GetEntryOk() (*NodeChildAssociation, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Entry, true
}

// SetEntry sets field value
func (o *NodeChildAssociationEntry) SetEntry(v NodeChildAssociation) {
	o.Entry = v
}

func (o NodeChildAssociationEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodeChildAssociationEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["entry"] = o.Entry
	return toSerialize, nil
}

type NullableNodeChildAssociationEntry struct {
	value *NodeChildAssociationEntry
	isSet bool
}

func (v NullableNodeChildAssociationEntry) Get() *NodeChildAssociationEntry {
	return v.value
}

func (v *NullableNodeChildAssociationEntry) Set(val *NodeChildAssociationEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableNodeChildAssociationEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableNodeChildAssociationEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodeChildAssociationEntry(val *NodeChildAssociationEntry) *NullableNodeChildAssociationEntry {
	return &NullableNodeChildAssociationEntry{value: val, isSet: true}
}

func (v NullableNodeChildAssociationEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodeChildAssociationEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


