/*
Alfresco Content Services REST API

**Core API**  Provides access to the core features of Alfresco Content Services. 

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RatingEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RatingEntry{}

// RatingEntry struct for RatingEntry
type RatingEntry struct {
	Entry Rating `json:"entry"`
}

// NewRatingEntry instantiates a new RatingEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRatingEntry(entry Rating) *RatingEntry {
	this := RatingEntry{}
	this.Entry = entry
	return &this
}

// NewRatingEntryWithDefaults instantiates a new RatingEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRatingEntryWithDefaults() *RatingEntry {
	this := RatingEntry{}
	return &this
}

// GetEntry returns the Entry field value
func (o *RatingEntry) GetEntry() Rating {
	if o == nil {
		var ret Rating
		return ret
	}

	return o.Entry
}

// GetEntryOk returns a tuple with the Entry field value
// and a boolean to check if the value has been set.
func (o *RatingEntry) GetEntryOk() (*Rating, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Entry, true
}

// SetEntry sets field value
func (o *RatingEntry) SetEntry(v Rating) {
	o.Entry = v
}

func (o RatingEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RatingEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["entry"] = o.Entry
	return toSerialize, nil
}

type NullableRatingEntry struct {
	value *RatingEntry
	isSet bool
}

func (v NullableRatingEntry) Get() *RatingEntry {
	return v.value
}

func (v *NullableRatingEntry) Set(val *RatingEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableRatingEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableRatingEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRatingEntry(val *RatingEntry) *NullableRatingEntry {
	return &NullableRatingEntry{value: val, isSet: true}
}

func (v NullableRatingEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRatingEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


