/*
Alfresco Content Services REST API

**Core API**  Provides access to the core features of Alfresco Content Services. 

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"github.com/ahuret/goalfresco/time"
)

// checks if the SharedLinkBodyCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SharedLinkBodyCreate{}

// SharedLinkBodyCreate struct for SharedLinkBodyCreate
type SharedLinkBodyCreate struct {
	NodeId string `json:"nodeId"`
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
}

// NewSharedLinkBodyCreate instantiates a new SharedLinkBodyCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSharedLinkBodyCreate(nodeId string) *SharedLinkBodyCreate {
	this := SharedLinkBodyCreate{}
	this.NodeId = nodeId
	return &this
}

// NewSharedLinkBodyCreateWithDefaults instantiates a new SharedLinkBodyCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSharedLinkBodyCreateWithDefaults() *SharedLinkBodyCreate {
	this := SharedLinkBodyCreate{}
	return &this
}

// GetNodeId returns the NodeId field value
func (o *SharedLinkBodyCreate) GetNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NodeId
}

// GetNodeIdOk returns a tuple with the NodeId field value
// and a boolean to check if the value has been set.
func (o *SharedLinkBodyCreate) GetNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NodeId, true
}

// SetNodeId sets field value
func (o *SharedLinkBodyCreate) SetNodeId(v string) {
	o.NodeId = v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *SharedLinkBodyCreate) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SharedLinkBodyCreate) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *SharedLinkBodyCreate) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given time.Time and assigns it to the ExpiresAt field.
func (o *SharedLinkBodyCreate) SetExpiresAt(v time.Time) {
	o.ExpiresAt = &v
}

func (o SharedLinkBodyCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SharedLinkBodyCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["nodeId"] = o.NodeId
	if !IsNil(o.ExpiresAt) {
		toSerialize["expiresAt"] = o.ExpiresAt
	}
	return toSerialize, nil
}

type NullableSharedLinkBodyCreate struct {
	value *SharedLinkBodyCreate
	isSet bool
}

func (v NullableSharedLinkBodyCreate) Get() *SharedLinkBodyCreate {
	return v.value
}

func (v *NullableSharedLinkBodyCreate) Set(val *SharedLinkBodyCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableSharedLinkBodyCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableSharedLinkBodyCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSharedLinkBodyCreate(val *SharedLinkBodyCreate) *NullableSharedLinkBodyCreate {
	return &NullableSharedLinkBodyCreate{value: val, isSet: true}
}

func (v NullableSharedLinkBodyCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSharedLinkBodyCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


