/*
Alfresco Content Services REST API

**Core API**  Provides access to the core features of Alfresco Content Services. 

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ProbeEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProbeEntry{}

// ProbeEntry struct for ProbeEntry
type ProbeEntry struct {
	Entry ProbeEntryEntry `json:"entry"`
}

// NewProbeEntry instantiates a new ProbeEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProbeEntry(entry ProbeEntryEntry) *ProbeEntry {
	this := ProbeEntry{}
	this.Entry = entry
	return &this
}

// NewProbeEntryWithDefaults instantiates a new ProbeEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProbeEntryWithDefaults() *ProbeEntry {
	this := ProbeEntry{}
	return &this
}

// GetEntry returns the Entry field value
func (o *ProbeEntry) GetEntry() ProbeEntryEntry {
	if o == nil {
		var ret ProbeEntryEntry
		return ret
	}

	return o.Entry
}

// GetEntryOk returns a tuple with the Entry field value
// and a boolean to check if the value has been set.
func (o *ProbeEntry) GetEntryOk() (*ProbeEntryEntry, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Entry, true
}

// SetEntry sets field value
func (o *ProbeEntry) SetEntry(v ProbeEntryEntry) {
	o.Entry = v
}

func (o ProbeEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProbeEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["entry"] = o.Entry
	return toSerialize, nil
}

type NullableProbeEntry struct {
	value *ProbeEntry
	isSet bool
}

func (v NullableProbeEntry) Get() *ProbeEntry {
	return v.value
}

func (v *NullableProbeEntry) Set(val *ProbeEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableProbeEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableProbeEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProbeEntry(val *ProbeEntry) *NullableProbeEntry {
	return &NullableProbeEntry{value: val, isSet: true}
}

func (v NullableProbeEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProbeEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


