/*
Alfresco Content Services REST API

**Core API**  Provides access to the core features of Alfresco Content Services. 

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SiteMembershipRequestWithPersonEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SiteMembershipRequestWithPersonEntry{}

// SiteMembershipRequestWithPersonEntry struct for SiteMembershipRequestWithPersonEntry
type SiteMembershipRequestWithPersonEntry struct {
	Entry SiteMembershipRequestWithPerson `json:"entry"`
}

// NewSiteMembershipRequestWithPersonEntry instantiates a new SiteMembershipRequestWithPersonEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSiteMembershipRequestWithPersonEntry(entry SiteMembershipRequestWithPerson) *SiteMembershipRequestWithPersonEntry {
	this := SiteMembershipRequestWithPersonEntry{}
	this.Entry = entry
	return &this
}

// NewSiteMembershipRequestWithPersonEntryWithDefaults instantiates a new SiteMembershipRequestWithPersonEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSiteMembershipRequestWithPersonEntryWithDefaults() *SiteMembershipRequestWithPersonEntry {
	this := SiteMembershipRequestWithPersonEntry{}
	return &this
}

// GetEntry returns the Entry field value
func (o *SiteMembershipRequestWithPersonEntry) GetEntry() SiteMembershipRequestWithPerson {
	if o == nil {
		var ret SiteMembershipRequestWithPerson
		return ret
	}

	return o.Entry
}

// GetEntryOk returns a tuple with the Entry field value
// and a boolean to check if the value has been set.
func (o *SiteMembershipRequestWithPersonEntry) GetEntryOk() (*SiteMembershipRequestWithPerson, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Entry, true
}

// SetEntry sets field value
func (o *SiteMembershipRequestWithPersonEntry) SetEntry(v SiteMembershipRequestWithPerson) {
	o.Entry = v
}

func (o SiteMembershipRequestWithPersonEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SiteMembershipRequestWithPersonEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["entry"] = o.Entry
	return toSerialize, nil
}

type NullableSiteMembershipRequestWithPersonEntry struct {
	value *SiteMembershipRequestWithPersonEntry
	isSet bool
}

func (v NullableSiteMembershipRequestWithPersonEntry) Get() *SiteMembershipRequestWithPersonEntry {
	return v.value
}

func (v *NullableSiteMembershipRequestWithPersonEntry) Set(val *SiteMembershipRequestWithPersonEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableSiteMembershipRequestWithPersonEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableSiteMembershipRequestWithPersonEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSiteMembershipRequestWithPersonEntry(val *SiteMembershipRequestWithPersonEntry) *NullableSiteMembershipRequestWithPersonEntry {
	return &NullableSiteMembershipRequestWithPersonEntry{value: val, isSet: true}
}

func (v NullableSiteMembershipRequestWithPersonEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSiteMembershipRequestWithPersonEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


