/*
Alfresco Content Services REST API

**Core API**  Provides access to the core features of Alfresco Content Services. 

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SiteGroupEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SiteGroupEntry{}

// SiteGroupEntry struct for SiteGroupEntry
type SiteGroupEntry struct {
	Entry SiteGroup `json:"entry"`
}

// NewSiteGroupEntry instantiates a new SiteGroupEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSiteGroupEntry(entry SiteGroup) *SiteGroupEntry {
	this := SiteGroupEntry{}
	this.Entry = entry
	return &this
}

// NewSiteGroupEntryWithDefaults instantiates a new SiteGroupEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSiteGroupEntryWithDefaults() *SiteGroupEntry {
	this := SiteGroupEntry{}
	return &this
}

// GetEntry returns the Entry field value
func (o *SiteGroupEntry) GetEntry() SiteGroup {
	if o == nil {
		var ret SiteGroup
		return ret
	}

	return o.Entry
}

// GetEntryOk returns a tuple with the Entry field value
// and a boolean to check if the value has been set.
func (o *SiteGroupEntry) GetEntryOk() (*SiteGroup, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Entry, true
}

// SetEntry sets field value
func (o *SiteGroupEntry) SetEntry(v SiteGroup) {
	o.Entry = v
}

func (o SiteGroupEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SiteGroupEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["entry"] = o.Entry
	return toSerialize, nil
}

type NullableSiteGroupEntry struct {
	value *SiteGroupEntry
	isSet bool
}

func (v NullableSiteGroupEntry) Get() *SiteGroupEntry {
	return v.value
}

func (v *NullableSiteGroupEntry) Set(val *SiteGroupEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableSiteGroupEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableSiteGroupEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSiteGroupEntry(val *SiteGroupEntry) *NullableSiteGroupEntry {
	return &NullableSiteGroupEntry{value: val, isSet: true}
}

func (v NullableSiteGroupEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSiteGroupEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


