/*
Alfresco Content Services REST API

**Core API**  Provides access to the core features of Alfresco Content Services. 

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SiteMembershipApprovalBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SiteMembershipApprovalBody{}

// SiteMembershipApprovalBody struct for SiteMembershipApprovalBody
type SiteMembershipApprovalBody struct {
	Role *string `json:"role,omitempty"`
}

// NewSiteMembershipApprovalBody instantiates a new SiteMembershipApprovalBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSiteMembershipApprovalBody() *SiteMembershipApprovalBody {
	this := SiteMembershipApprovalBody{}
	return &this
}

// NewSiteMembershipApprovalBodyWithDefaults instantiates a new SiteMembershipApprovalBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSiteMembershipApprovalBodyWithDefaults() *SiteMembershipApprovalBody {
	this := SiteMembershipApprovalBody{}
	return &this
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *SiteMembershipApprovalBody) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteMembershipApprovalBody) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *SiteMembershipApprovalBody) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *SiteMembershipApprovalBody) SetRole(v string) {
	o.Role = &v
}

func (o SiteMembershipApprovalBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SiteMembershipApprovalBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	return toSerialize, nil
}

type NullableSiteMembershipApprovalBody struct {
	value *SiteMembershipApprovalBody
	isSet bool
}

func (v NullableSiteMembershipApprovalBody) Get() *SiteMembershipApprovalBody {
	return v.value
}

func (v *NullableSiteMembershipApprovalBody) Set(val *SiteMembershipApprovalBody) {
	v.value = val
	v.isSet = true
}

func (v NullableSiteMembershipApprovalBody) IsSet() bool {
	return v.isSet
}

func (v *NullableSiteMembershipApprovalBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSiteMembershipApprovalBody(val *SiteMembershipApprovalBody) *NullableSiteMembershipApprovalBody {
	return &NullableSiteMembershipApprovalBody{value: val, isSet: true}
}

func (v NullableSiteMembershipApprovalBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSiteMembershipApprovalBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


