/*
Alfresco Content Services REST API

**Core API**  Provides access to the core features of Alfresco Content Services. 

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RatingBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RatingBody{}

// RatingBody struct for RatingBody
type RatingBody struct {
	// The rating scheme type. Possible values are likes and fiveStar.
	Id string `json:"id"`
	// The rating. The type is specific to the rating scheme, boolean for the likes and an integer for the fiveStar
	MyRating string `json:"myRating"`
}

// NewRatingBody instantiates a new RatingBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRatingBody(id string, myRating string) *RatingBody {
	this := RatingBody{}
	this.Id = id
	this.MyRating = myRating
	return &this
}

// NewRatingBodyWithDefaults instantiates a new RatingBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRatingBodyWithDefaults() *RatingBody {
	this := RatingBody{}
	var id string = "likes"
	this.Id = id
	return &this
}

// GetId returns the Id field value
func (o *RatingBody) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RatingBody) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RatingBody) SetId(v string) {
	o.Id = v
}

// GetMyRating returns the MyRating field value
func (o *RatingBody) GetMyRating() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MyRating
}

// GetMyRatingOk returns a tuple with the MyRating field value
// and a boolean to check if the value has been set.
func (o *RatingBody) GetMyRatingOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MyRating, true
}

// SetMyRating sets field value
func (o *RatingBody) SetMyRating(v string) {
	o.MyRating = v
}

func (o RatingBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RatingBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["myRating"] = o.MyRating
	return toSerialize, nil
}

type NullableRatingBody struct {
	value *RatingBody
	isSet bool
}

func (v NullableRatingBody) Get() *RatingBody {
	return v.value
}

func (v *NullableRatingBody) Set(val *RatingBody) {
	v.value = val
	v.isSet = true
}

func (v NullableRatingBody) IsSet() bool {
	return v.isSet
}

func (v *NullableRatingBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRatingBody(val *RatingBody) *NullableRatingBody {
	return &NullableRatingBody{value: val, isSet: true}
}

func (v NullableRatingBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRatingBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


