/*
Alfresco Content Services REST API

**Core API**  Provides access to the core features of Alfresco Content Services. 

API version: 1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SiteRoleEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SiteRoleEntry{}

// SiteRoleEntry struct for SiteRoleEntry
type SiteRoleEntry struct {
	Entry SiteRole `json:"entry"`
}

// NewSiteRoleEntry instantiates a new SiteRoleEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSiteRoleEntry(entry SiteRole) *SiteRoleEntry {
	this := SiteRoleEntry{}
	this.Entry = entry
	return &this
}

// NewSiteRoleEntryWithDefaults instantiates a new SiteRoleEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSiteRoleEntryWithDefaults() *SiteRoleEntry {
	this := SiteRoleEntry{}
	return &this
}

// GetEntry returns the Entry field value
func (o *SiteRoleEntry) GetEntry() SiteRole {
	if o == nil {
		var ret SiteRole
		return ret
	}

	return o.Entry
}

// GetEntryOk returns a tuple with the Entry field value
// and a boolean to check if the value has been set.
func (o *SiteRoleEntry) GetEntryOk() (*SiteRole, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Entry, true
}

// SetEntry sets field value
func (o *SiteRoleEntry) SetEntry(v SiteRole) {
	o.Entry = v
}

func (o SiteRoleEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SiteRoleEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["entry"] = o.Entry
	return toSerialize, nil
}

type NullableSiteRoleEntry struct {
	value *SiteRoleEntry
	isSet bool
}

func (v NullableSiteRoleEntry) Get() *SiteRoleEntry {
	return v.value
}

func (v *NullableSiteRoleEntry) Set(val *SiteRoleEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableSiteRoleEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableSiteRoleEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSiteRoleEntry(val *SiteRoleEntry) *NullableSiteRoleEntry {
	return &NullableSiteRoleEntry{value: val, isSet: true}
}

func (v NullableSiteRoleEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSiteRoleEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


